apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    version: v1
spec:
  replicas: 1
  selector:
    # selector to match the pod
    matchLabels:
      app: app1
      version: v1
  template:
    metadata:
      labels:
        app: app1
        version: v1
    spec:
      serviceAccountName: service-account1
      containers:
        - name: app1
          image: app1
          # never pull the image (because it's local)
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "600Mi"
              cpu: "1000m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    version: v1
spec:
  replicas: 1
  selector:
    # selector to match the pod
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      labels:
        app: app2
        version: v1
    spec:
      serviceAccountName: service-account2
      containers:
        - name: app2
          image: app2
          # never pull the image (because it's local)
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "600Mi"
              cpu: "1000m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
    version: v1
spec:
  replicas: 1
  selector:
    # selector to match the pod
    matchLabels:
      app: app3
      version: v1
  template:
    metadata:
      labels:
        app: app3
        version: v1
    spec:
      serviceAccountName: service-account3
      containers:
        - name: app3
          image: app3
          # never pull the image (because it's local)
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "600Mi"
              cpu: "1000m"