apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8001'
  name: fastapi1
spec:
  selector:
    app: fastapi1
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8001'
  name: fastapi2
spec:
  selector:
    app: fastapi2
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8001'
  name: fastapi3
spec:
  selector:
    app: fastapi3
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001