apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '1323'
  name: app1
spec:
  selector:
    app: app1
  ports:
    - name: http
      protocol: TCP
      port: 1323
      targetPort: 1323

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '1323'
  name: app2
spec:
  selector:
    app: app2
  ports:
    - name: http
      protocol: TCP
      port: 1323
      targetPort: 1323

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '1323'
  name: app3
spec:
  selector:
    app: app3
  ports:
    - name: http
      protocol: TCP
      port: 1323
      targetPort: 1323