{
 "title": "Requests",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Successful requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "istio_requests_total{response_code=\"200\"}",
     "legendFormat": "{{app}} -> {{destination_app}} | Policy: {{connection_security_policy}} | Code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "istio_requests_total{response_code!=\"200\"}",
     "legendFormat": "{{app}} -> {{destination_app}} | Policy: {{connection_security_policy}} | Code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Requests app2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "istio_requests_total{destination_app=\"app2\"}",
     "legendFormat": "{{app}} -> {{destination_app}} | Policy: {{connection_security_policy}} | Code: {{response_code}}"
    }
   ]
  },
  {
   "title": "Request Duration in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "istio_request_duration_milliseconds_bucket{destination_service_namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}