# Istio Observability
- name: Setup Observability for Istio
  debug:
    msg: "Setting up Observability for Istio..."

- name: Enable metrics-server Addon
  command: minikube addons enable metrics-server
- name: Set metric resolution to 10s (=minimum)
  command: >
    kubectl patch deployment metrics-server -n kube-system --type='json' -p='[{
      "op": "replace",
      "path": "/spec/template/spec/containers/0/args",
      "value": [
        "--cert-dir=/tmp",
        "--secure-port=4443",
        "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
        "--kubelet-use-node-status-port",
        "--metric-resolution=10s",
        "--kubelet-insecure-tls"
      ]
    }]'

- name: Set Up Prometheus
  command: kubectl apply -f kubernetes/istio/observability/prometheus.yaml
  args:
    chdir: "{{ path }}"

- name: Set Up Kiali
  command: helm install --namespace istio-system --set auth.strategy="anonymous" --repo https://kiali.org/helm-charts kiali-server kiali-server

- name: Set Up Grafana
  command: kubectl apply -f kubernetes/istio/observability/grafana.yaml
  args:
    chdir: "{{ path }}"

- name: Alert user to import config file in /config into Grafana
  debug:
    msg: Import the dashboard json file from config/Requests-1703960621987.json
  
- name: Inform user to open Kiali dashboard
  debug:
    msg: command':' istioctl d kiali

