# Istio Observability
- name: Setup Observability for Istio
  debug:
    msg: "Setting up Observability for Istio..."

- name: Enable metrics-server Addon
  command: minikube addons enable metrics-server

- name: Set Up Prometheus
  command: kubectl apply -f kubernetes/istio/prometheus.yaml
  args:
    chdir: "{{ path }}"

- name: Set Up Jaeger
  command: kubectl apply -f kubernetes/istio/jaeger.yaml
  args:
    chdir: "{{ path }}"

- name: Set Up Kiali
  command: helm install --namespace istio-system --set auth.strategy="anonymous" --repo https://kiali.org/helm-charts kiali-server kiali-server

- name: Set Up Grafana
  command: kubectl apply -f kubernetes/istio/grafana.yaml
  args:
    chdir: "{{ path }}"

- name: Enable tracing and set sample rate to 100%
  command: istioctl install -f kubernetes/istio/istioctl/tracing.yaml -y
  args:
    chdir: "{{ path }}"

# Restart pods again one after the other instead of simultaneously to distribute request times
- name: Restart Pod 1
  command: kubectl delete pod -l app=app1 -n default

- name: Restart Pod 2
  command: kubectl delete pod -l app=app2 -n default

- name: Restart Pod 3
  command: kubectl delete pod -l app=app3 -n default

- name: Alert user to import config file in /config into Grafana
  debug:
    msg: Import the dashboard json file from config/Requests-1703960621987.json

- name: Alert user to use Jaeger URL
  debug:
    msg: Query URL for Jaeger':' http://tracing.istio-system.svc.cluster.local:80
  
- name: Inform user to open Kiali dashboard
  debug:
    msg: command':' istioctl d kiali

- name: Start metric gathering script (10 minutes)
  command: python data/node_metrics.py 10
  args:
    chdir: "{{ path }}"