apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  namespace: default
  annotations:
    konghq.com/plugins: jwt
spec:
  ingressClassName: "kong"
  rules:
  - http:
      paths:
      - path: /action
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 1323

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2-ingress
  namespace: default
  annotations:
    konghq.com/plugins: jwt
spec:
  ingressClassName: "kong"
  rules:
  - http:
      paths:
      - path: /action
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 1323

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3-ingress
  namespace: default
  annotations:
    konghq.com/plugins: jwt
spec:
  ingressClassName: "kong"
  rules:
  - http:
      paths:
      - path: /action
        pathType: Prefix
        backend:
          service:
            name: app3
            port:
              number: 1323