---
- name: Bachelor Project Setup Playbook
  hosts: localhost
  gather_facts: no
  vars:
    # Root Path
    path: "/Users/christoph/Code/FH/5. Semester/Individualprojekt"
  vars_prompt:
    - name: setup
      prompt: "Set up and configure Istio, Kong or Vanilla? (i/k/v)"
      private: no


  tasks:
    - block:
    # Setup minikube cluster
      - name: Start Docker Desktop
        command: open -j /Applications/Docker.app

      - name: Stop Minikube Cluster
        command: minikube stop
        ignore_errors: yes
        register: minikube_stop_result
      - name: Check if stopping minikube failed due to it not running
        fail:
          msg: "Failed to stop minikube. Error: {{ minikube_stop_result.stdout }}"
        when: minikube_stop_result.failed and ("Profile \"minikube\" not found" not in minikube_stop_result.stdout)

      - name: Delete Minikube Cluster
        command: minikube delete
        ignore_errors: no
        register: minikube_delete_result
      - name: Check if deleten minikube failed due to non existing profile
        fail:
          msg: "Failed to delete minikube profile. Error: {{ minikube_delete_result.stdout }}"
        when: minikube_delete_result.failed and ('No minikube profile was found' not in minikube_delete_result.stdout)

      - name: Start Minikube
        command: minikube start --memory=8192mb --cpus=4

      - name: Build Docker Image
        command: docker build -t fastapi .
        args:
         chdir: "{{ path }}"

      # - name: Build Docker Image
      #   docker_image:
      #     name: fastapi
      #     build:
      #       path: "{{ path }}"
      #     source: build
      #   register: docker_build_result


      - name: Save to fastapi.tar
        command: docker save --output fastapi.tar fastapi
        args:
         chdir: "{{ path }}"

      # - name: Save Docker Image
      #   command: docker save -o fastapi.tar fastapi
      #   args:
      #     chdir: "{{ path }}"
      #   when: docker_build_result.changed

      - name: Load Image into Minikube VM
        command: minikube image load fastapi.tar
        args:
          chdir: "{{ path }}"


    - block:
      # Deploy Kubernetes Components
      - name: Create Kubernetes Services
        command: kubectl create -f kubernetes/services.yaml
        args:
          chdir: "{{ path }}"

      - name: Create Service Accounts
        command: kubectl create -f kubernetes/service-accounts.yaml
        args:
          chdir: "{{ path }}"

      - name: Create Deployments
        command: kubectl create -f kubernetes/deployments.yaml
        args:
          chdir: "{{ path }}"


    - block:
      - include_tasks: istio.yaml
        when: setup == 'i'

    - block:
      - include_tasks: istio-observability.yaml
        when: setup == 'i'

    - block:
      - include_tasks: kong.yaml
      when: setup == 'k'

    - block:
      - include_tasks: observability.yaml
      when: setup == 'k' or setup == 'v'